# If using AWS Control Tower, ensure that all the specified Organizational Units (OU)
# have been created and enrolled as the accelerator will verify that the OU layout
# matches before continuing to execute the deployment pipeline.
enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: Tenant
  - name: Tenant-HIS
  
quarantineNewAccounts:
  enable: true
  scpPolicyName: Quarantine
serviceControlPolicies:
  - name: AcceleratorGuardrails1
    description: >
      Accelerator GuardRails 1
    policy: service-control-policies/guardrails-1.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Root
  - name: AcceleratorGuardrails2
    description: >
      Accelerator GuardRails 2
    policy: service-control-policies/guardrails-2.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Root
  - name: AcceleratorGuardrails3
    description: >
      Prevent Accounts from leaving Org. Enforce S3 Block Public Access.
    policy: service-control-policies/guardrails-3.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Root
  - name: Accelerator-HIPAA
    description: >
      Enforce only HIPAA eligible services.
    policy: service-control-policies/scp-hlc-hipaa-service.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: []

  - name: Quarantine
    description: >
      This SCP is used to prevent changes to new accounts until the Accelerator
      has been executed successfully.
      This policy will be applied upon account creation if enabled.
    policy: service-control-policies/quarantine.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: []
taggingPolicies:
  - name: TagPolicy
    description: Organization Tagging Policy
    policy: tagging-policies/org-tag-policy.json
    deploymentTargets:
      organizationalUnits:
        - Root
  - name: phi-tag-policy
    description: Healthcare Organization Tagging Policy
    policy: tagging-policies/healthcare-org-tag-policy.json
    deploymentTargets:
      organizationalUnits:
        - Tenant-HIS
backupPolicies:
  - name: BackupPolicy
    description: Organization Backup Policy
    policy: backup-policies/backup-plan.json
    deploymentTargets:
      organizationalUnits:
        - Root
