###############################################################################################################
# For additional configurable services, features, and property descriptions,                                  #
# please review class GlobalConfig reference in our TypeDoc:                                                  #
# https://awslabs.github.io/landing-zone-accelerator-on-aws/classes/_aws_accelerator_config.GlobalConfig.html #
###############################################################################################################

homeRegion: &HOME_REGION us-gov-west-1
enabledRegions:
  - *HOME_REGION
managementAccountAccessRole: AWSControlTowerExecution
# Update the retention time based on compliance and auditing requirements
# Defining and storing cloudwatch logs for 365 days
cloudwatchLogRetentionInDays: 365
terminationProtection: true
cdkOptions:
  centralizeBuckets: true
  useManagementAccessRole: true
snsTopics:
  deploymentTargets:
    organizationalUnits:
      - Root
  topics:
    - name: Security
      emailAddresses:
        - <security-notifications>@example.com  <----- UPDATE EMAIL ADDRESS
controlTower:
  enable: true
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
    organizationTrailSettings:
      multiRegionTrail: true
      globalServiceEvents: true
      managementEvents: true
      s3DataEvents: true
      lambdaDataEvents: true
      sendToCloudWatchLogs: true
      apiErrorRateInsight: false
      apiCallRateInsight: false
  sessionManager:
    sendToCloudWatchLogs: false
    sendToS3: true
    attachPolicyToIamRoles:
      - EC2-Default-SSM-AD-Role
  cloudwatchLogs:
    dynamicPartitioning: dynamic-partitioning/log-filters.json
  accessLogBucket:
    # Update the retention time based on compliance and auditing requirements
    # Defining and storing access log Bucket for 365 days
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 365
        noncurrentVersionExpiration: 365
  centralLogBucket:
    # Defining and storing storing log Bucket for 365 days
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 365
        noncurrentVersionExpiration: 365
    s3ResourcePolicyAttachments:
      - policy: bucket-policies/central-log-bucket.json
  elbLogBucket:
    # Defining and storing storing log Bucket for 365 days
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 7
        expiration: 365
        noncurrentVersionExpiration: 365
