enable: true
organizationalUnits:
  - name: Security
  - name: Infrastructure
  - name: GovCloud
quarantineNewAccounts:
  enable: true
  scpPolicyName: Quarantine
serviceControlPolicies:
  # this policy prevents the use of commercial accounts that are tied to GovCloud
  # only actions by organization root management role AWSControlTowerExecution,
  # cdk and landing zone accelerator roles are allowed.
  # Further, API calls from AWS Service is also allowed via PrincipalIsAWSService boolean
  # this allows background services like billingreports.amazonaws.com
  # to make the calls to the account but prevents admins to launch any workloads.
  # It is highly recommended to leave these commercial accounts locked down
  - name: Lockdown paired account
    description: Paired commercial accounts tied to GovCloud locked down
    policy: service-control-policies/lockdown-govCloud-accounts.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - GovCloud
  - name: Quarantine
    description: >
      This SCP is used to prevent changes to new accounts until the Accelerator
      has been executed successfully.
      This policy will be applied upon account creation if enabled.
    policy: service-control-policies/quarantine.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: []
taggingPolicies: []
backupPolicies: []
